[camera]
mouse_sensitivity_x = 8e-4
mouse_sensitivity_y = 5e-4

[camera.fixed_angle]
min_distance = 10.0
max_distance = 20.0
zoom_speed = 0.7
rotation_smoothing = 1.0
translation_smoothing = 0.9
zoom_in_smoothing = 0.2
zoom_out_smoothing = 1.2
pitch = -80.0

[camera.first_person]
translation_smoothing = 0.05
rotation_smoothing = 0.1
max_pitch = 80
min_pitch = -80
tracking_smoothing = 1.5

[camera.third_person]
translation_smoothing = 0.9
rotation_smoothing = 0.5
tracking_smoothing = 0.8
max_pitch = 80
min_pitch = -80
min_distance = 1.0
max_distance = 10.0
zoom_speed = 0.7
min_distance_to_objects = 4e-1
zoom_in_smoothing = 0.2
zoom_out_smoothing = 1.2

[characters]
model_sync_smoothing = 0.15
rotation_smoothing = 1.0

[player]
rotate_to_speaker_smoothness = 3.0
sprint_effect_speed_threshold = 7.0
fov_saturation_speed = 12.0
min_fov = 0.75
max_fov = 1.5

[dialog]
base_letters_per_second = 60.0
